name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:       
    - "target"
    - "dbt_modules"


models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: view

    