name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "CREATE DATABASE IF NOT EXISTS analytics"
  - "CREATE DATABASE IF NOT EXISTS raw_data"

models:
  jaffle_shop:
    +database: analytics

    staging:
      +materialized: view
      +schema: raw1
      +database: raw_data

    marts:
      +materialized: table
      +schema: marts

seeds:
  jaffle_shop:
    +database: raw_data