<<<<<<< HEAD
default:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'RAW') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'JAFFLE_SHOP') }}"
      threads: 1
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'INGEST') }}"
  target: dev
=======
analytics:              # must match `profile: analytics`
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN        # or a more restricted role you actually use
      warehouse: COMPUTE_WH     # or your training warehouse name
      database: RAW             # your database
      schema: JAFFLE_SHOP       # existing schema in RAW
      threads: 4
      account: ""               # allowed to be blank / dummy for dbt Projects
      user: ""
>>>>>>> 9502d61816376e2e3ab92ec29099303ec64d03b0
